### PR TITLE
Puneet2019/sorted list fix

### LINKED ISSUE #270: Add and Remove methods not working inside listData

### PR DESCRIPTION
**Pull request by puneet2019**
closes #270

### CODE REVIEW

File: schema/types/base/listData.go [hunk 1]
```diff
@@ -27,12 +27,14 @@ func (listData listData) Compare(data types.Data) int {
 		panic(Error)
 	}
 
-	difference := 0
 	for i, compareData := range compareListData.Value {
-		difference += listData.Value[i].Compare(compareData)
+		result := listData.Value[i].Compare(compareData)
+		if result != 0 {
+			return result
+		}
```
Comment (puneet2019) [inline schema/types/base/listData.go:34]: expensive but can change to 
```
func (listData listData) Compare(data types.Data) int {
	compareListData, Error := listDataFromData(data)
	if Error != nil {
		panic(Error)
	}

	listDataString :=  []string{}
	for _, data := range listData.Value{
		listDataString = append(listDataString, data.String())
	}

	comparisonDataString :=  []string{}
	for _, data := range compareListData.Value{
		comparisonDataString = append(comparisonDataString, data.String())
	}
	
	return strings.Compare(strings.Join(listDataString, constants.ListDataStringSeparator), strings.Join(comparisonDataString, constants.ListDataStringSeparator))
}
```
for correctness

**Review by deepanshutr — DISMISSED** [review]
Reviewed.

**Review by deepanshutr — APPROVED** [review]
Reviewed.
