### PR TITLE
fixing GetSignBytes codec marshaling for all transactions.

### LINKED ISSUE #162: PersistenceSDK msgs and tendemint/Sig do not create same signatures.
The packageCodec defined in internal/common of each module, does not register message structs of transactions and is being used to Marshal the struct. 

branch - master
commit - eb6bc10c8b9c3a6742c6b13658920b5a69b71ea4

### PR DESCRIPTION
**Pull request by puneet2019**
closes #162

Need a better way to do this

### CODE REVIEW

File: modules/assets/internal/transactions/burn/message.go [hunk 1]
```diff
@@ -11,11 +11,11 @@ import (
 	sdkTypes "github.com/cosmos/cosmos-sdk/types"
 	"github.com/cosmos/cosmos-sdk/types/errors"
 	xprtErrors "github.com/persistenceOne/persistenceSDK/constants/errors"
-	"github.com/persistenceOne/persistenceSDK/modules/assets/internal/common"
 	"github.com/persistenceOne/persistenceSDK/modules/assets/internal/module"
 	"github.com/persistenceOne/persistenceSDK/schema/helpers"
 	"github.com/persistenceOne/persistenceSDK/schema/types"
 	codecUtilities "github.com/persistenceOne/persistenceSDK/utilities/codec"
+	messageUtilities "github.com/persistenceOne/persistenceSDK/utilities/message"
```
Comment (deepanshutr) [inline modules/assets/internal/transactions/burn/message.go:18]: should go inside utilites/codec

**Review by deepanshutr — APPROVED** [review]
Reviewed, added comments, will correct in the next PR.
